/*
 * Auto-generated by Frida. Please modify to match the signature of WriteFile.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('WriteFile() in kernelbase.');
    var guessedString = Memory.readAnsiString(args[1]);
    log("Guessed string: " + guessedString);
  },

  onLeave(log, retval, state) {
    log("Left WriteFile (kernelbase)");
  }
});
