/*
 * Auto-generated by Frida. Please modify to match the signature of CreateFileA.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('CreateFileA() in kernel32');
    var newPath = Memory.allocAnsiString("C:\\Users\\jacob\\OneDrive\\Desktop\\Code\\ctf\\binket2");
    args[0] = newPath;  // override the pointer to the new valid path
    log("Modified filename to: " + Memory.readAnsiString(args[0]));
  },

  onLeave(log, retval, state) {
    log("Left CreateFileA() in kernel32");
  }
});
